title: omt2025's Homepage
page-top-title: Runming
top-section-bg-text: A journey of a thousand miles begins with a single step. —— Lao Tzu
home-subtitle: Runming Yan&ensp;|&ensp;闫润明
copyright-text: '&copy; Runming 2023-2025. All Rights Reserved.'
